### ISSUE TITLE
We don't look for the string "alpha-dev"

### ISSUE THREAD

**Issue by intchloe** [redpois0n/relayrewards#10]
https://globe.torproject.org/#/relay/9695DFC35FFEB861329B9F1AB04C46397020CE31
https://www.relayawards.com/relay.php?fp=9695DFC35FFEB861329B9F1AB04C46397020CE31

**Comment by wille** [comment]
https://github.com/redpois0n/relayawards/commit/2d66c5de3767000fc0f52818326a76a0ea005aed
