### ISSUE TITLE
Implement a "Fresh Onions" badge

### ISSUE THREAD

**Issue by alxndr42** [redpois0n/relayrewards#12]
Please give a badge to relays running the latest stable release of Tor.

Related to #11

**Comment by wille** [comment]
https://github.com/redpois0n/relayawards/commit/0e08411b55733560f72f9c821bb5e0f7c0191d1b

**Comment by alxndr42** [comment]
The original idea was to look for the _latest_ stable release being run. Unfortunately I don't know if the version number is published anywhere in a format that's easily machine-readable, or if one would have to check the `dist` folder.
