### ISSUE TITLE
Awards Points

### ISSUE THREAD

**Issue by intchloe** [redpois0n/relayrewards#5]
Exotic - 5
Alpha - 1
Unix - 1
Contact - 2
IPV6 - 2
HTTPS Lover - 2

Uptime 10 - 1
Uptime 20 - 2
Uptime 50 - 3
Uptime 150 - 4
Uptime 1Y - 10
Uptime 2Y - 50

Lightning 0 - 1 <- NOTE: this is a new award. 
Lightning 1 - 2
Lightning 10 - 3
Lightning 15 - 4 
Lightning 25 - 5
Lightning 50 - 10
Lightning 75 - 50

Guard Probability 1 - 1
Guard Probability 2 - 2
Guard Probability 3 - 10
Guard Probability 4 - 20

Exit Probability 1 - 1
Exit Probability 2 - 2
Exit Probability 3 - 10
Exit Probability 4 - 20

Middle Probability 1 - 1 
Middle Probability 2 - 2
Middle Probability 3 - 10
Middle Probability 4 - 20

**Comment by wille** [comment]
@intchloe you will need to update the point in exit_probability.php etc, since we have 6 levels and you only specified 4. Please wait until it is complete on my side first.

**Comment by wille** [comment]
Everything except consensus weight icons are added
