### ISSUE TITLE
Add these awards

### ISSUE THREAD

**Issue by intchloe** [redpois0n/relayrewards#6]
Lightning 0 - 1 MB/s or more in bandwidth speed
Guard Probability 0 - Over 0.01% mean guard probability fraction
Exit Probability 0 - Over 0.01% mean exit probability fraction
Middle Probability 0 - Over 0.01% mean middle probability fraction

Icon for them all is attached. Blue for Probability and yellow for lightning. 

![exit_prob_0](https://cloud.githubusercontent.com/assets/7259227/14476946/21191eea-010b-11e6-95d9-9e89e862f36c.png)
![guard_prob_0](https://cloud.githubusercontent.com/assets/7259227/14476947/211ae5cc-010b-11e6-86c8-02cca9695559.png)
![middle_prob](https://cloud.githubusercontent.com/assets/7259227/14476948/211c4084-010b-11e6-8a45-92727757a614.png)
![1_mb_speed](https://cloud.githubusercontent.com/assets/7259227/14476949/211dfd3e-010b-11e6-8a15-3a6b4ca4ec42.png)

**Comment by wille** [comment]
Fixed in https://github.com/redpois0n/relayawards/commit/47112c9cb9d97156920942bda6157192694db5da

Guard and Exit probability awards for 0.01% already exists

**Comment by intchloe** [comment]
Sorry, I meant 0.001
