### ISSUE TITLE
Better search

### ISSUE THREAD

**Issue by intchloe** [redpois0n/relayrewards#9]
The search function needs to get better. You should be able to search on continents too, such as Europe, South America and Africa. We can have arrays containing all the countries per continents so that's not a problem. 

Also, search on only country would be good too. Another search-parameter for that maybe? 

And, we should implement "AND" logic in the search. For instance, If me and my friend are having a competition I should be able to search on Chloe+otherelayname

**Comment by wille** [comment]
You will need to fix the continent arrays, and I'll happily implement them.

**Comment by intchloe** [comment]
**Europe**: 

AL,AD,AT,BY,BE,BA,BG,HR,CY,CZ,DK,EE,FO,FI,FR,DE,GI,GR,HU,IS,IE,IT,LV,LI,LT,LU,MK,MT,MD,MC,NL,NO,PL,PT,RO,RU,SM,RS,SK,SI,ES,SE,CH,UA,GB,VA,RS,IM,RS,ME

**Africa**

DZ,AO,SH,BJ,BW,BF,BI,CM,CV,CF,TD,KM,CG,DJ,EG,GQ,ER,ET,GA,GM,GH,GW,GN,CI,KE,LS,LR,LY,MG,MW,ML,MR,MU,YT,MA,MZ,NA,NE,NG,ST,RE,RW,ST,SN,SC,SL,SO,ZA,SH,SD,SZ,TZ,TG,TN,UG,CD,ZM,TZ,ZW,SS,CD

**Asia**: 

AF,AM,AZ,BH,BD,BT,BN,KH,CN,CX,CC,IO,GE,HK,IN,ID,IR,IQ,IL,JP,JO,KZ,KP,KR,KW,KG,LA,LB,MO,MY,MV,MN,MM,NP,OM,PK,PH,QA,SA,SG,LK,SY,TW,TJ,TH,TR,TM,AE,UZ,VN,YE,PS

**North America**

AI,AG,AW,BS,BB,BZ,BM,VG,CA,KY,CR,CU,CW,DM,DO,SV,GL,GD,GP,GT,HT,HN,JM,MQ,MX,PM,MS,CW,KN,NI,PA,PR,KN,LC,PM,VC,TT,TC,VI,US,SX,BQ,SA

**South America**

AR,BO,BR,CL,CO,EC,FK,GF,GY,GY,PY,PE,SR,UY,VE

**Comment by wille** [comment]
You can now search on multiple strings, just split the search term with a +

**Comment by intchloe** [comment]
Are these fixed? cc @redpois0n

**Comment by wille** [comment]
No, fix these in this format and I will implement them

``` php
$continents = [
       "europe" => [ "SE", "NO", "GB" .... ],
       "north america" => [ ... ],
       .......
];
```

**Comment by Idomin** [comment]
Uploaded file with the $continents list fixed.

[continents.txt](https://github.com/redpois0n/relayawards/files/345162/continents.txt)

**Comment by wille** [comment]
https://github.com/redpois0n/relayawards/commit/ac1615dd8d40c973c74339f4c7e490487de4fc49
